package com.pdd.userMgr.service.mapper;

import com.pdd.userMgr.service.po.StoreUser;
import com.pdd.userMgr.service.po.StoreUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user
     *
     * @mbggenerated
     */
    int countByExample(StoreUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user
     *
     * @mbggenerated
     */
    int deleteByExample(StoreUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user
     *
     * @mbggenerated
     */
    int insert(StoreUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user
     *
     * @mbggenerated
     */
    int insertSelective(StoreUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user
     *
     * @mbggenerated
     */
    List<StoreUser> selectByExample(StoreUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user
     *
     * @mbggenerated
     */
    StoreUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StoreUser record, @Param("example") StoreUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StoreUser record, @Param("example") StoreUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StoreUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StoreUser record);
}