package com.pdd.userMgr.service.mapper;

import com.pdd.userMgr.service.po.StoreUserRecord;
import com.pdd.userMgr.service.po.StoreUserRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreUserRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user_record
     *
     * @mbggenerated
     */
    int countByExample(StoreUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user_record
     *
     * @mbggenerated
     */
    int deleteByExample(StoreUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user_record
     *
     * @mbggenerated
     */
    int insert(StoreUserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user_record
     *
     * @mbggenerated
     */
    int insertSelective(StoreUserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user_record
     *
     * @mbggenerated
     */
    List<StoreUserRecord> selectByExample(StoreUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user_record
     *
     * @mbggenerated
     */
    StoreUserRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StoreUserRecord record, @Param("example") StoreUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StoreUserRecord record, @Param("example") StoreUserRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StoreUserRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_user_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StoreUserRecord record);
}