package com.pdd.shopMgr.service.mapper;

import com.pdd.shopMgr.service.po.StoreDict;
import com.pdd.shopMgr.service.po.StoreDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_dict
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int countByExample(StoreDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_dict
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int deleteByExample(StoreDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_dict
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_dict
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int insert(StoreDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_dict
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int insertSelective(StoreDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_dict
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    List<StoreDict> selectByExample(StoreDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_dict
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    StoreDict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_dict
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") StoreDict record, @Param("example") StoreDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_dict
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByExample(@Param("record") StoreDict record, @Param("example") StoreDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_dict
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByPrimaryKeySelective(StoreDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_dict
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByPrimaryKey(StoreDict record);
}