package com.pdd.shopMgr.service.mapper;

import com.pdd.shopMgr.service.po.StoreArea;
import com.pdd.shopMgr.service.po.StoreAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_area
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int countByExample(StoreAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_area
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int deleteByExample(StoreAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_area
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_area
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int insert(StoreArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_area
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int insertSelective(StoreArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_area
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    List<StoreArea> selectByExample(StoreAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_area
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    StoreArea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_area
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") StoreArea record, @Param("example") StoreAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_area
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByExample(@Param("record") StoreArea record, @Param("example") StoreAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_area
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByPrimaryKeySelective(StoreArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_area
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByPrimaryKey(StoreArea record);
}