package com.pdd.shopMgr.service.mapper;

import com.pdd.shopMgr.service.po.StoreShopGoodsRelation;
import com.pdd.shopMgr.service.po.StoreShopGoodsRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreShopGoodsRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop_goods_relation
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int countByExample(StoreShopGoodsRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop_goods_relation
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int deleteByExample(StoreShopGoodsRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop_goods_relation
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop_goods_relation
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int insert(StoreShopGoodsRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop_goods_relation
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int insertSelective(StoreShopGoodsRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop_goods_relation
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    List<StoreShopGoodsRelation> selectByExample(StoreShopGoodsRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop_goods_relation
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    StoreShopGoodsRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop_goods_relation
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") StoreShopGoodsRelation record, @Param("example") StoreShopGoodsRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop_goods_relation
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByExample(@Param("record") StoreShopGoodsRelation record, @Param("example") StoreShopGoodsRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop_goods_relation
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByPrimaryKeySelective(StoreShopGoodsRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop_goods_relation
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByPrimaryKey(StoreShopGoodsRelation record);
}