package com.pdd.shopMgr.service.mapper;

import com.pdd.shopMgr.service.po.StoreShop;
import com.pdd.shopMgr.service.po.StoreShopExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int countByExample(StoreShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int deleteByExample(StoreShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int insert(StoreShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int insertSelective(StoreShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    List<StoreShop> selectByExample(StoreShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    StoreShop selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") StoreShop record, @Param("example") StoreShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByExample(@Param("record") StoreShop record, @Param("example") StoreShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByPrimaryKeySelective(StoreShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_shop
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByPrimaryKey(StoreShop record);
}