package com.pdd.shopMgr.service.mapper;

import com.pdd.shopMgr.service.po.StoreGoods;
import com.pdd.shopMgr.service.po.StoreGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int countByExample(StoreGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int deleteByExample(StoreGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int insert(StoreGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int insertSelective(StoreGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    List<StoreGoods> selectByExampleWithBLOBs(StoreGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    List<StoreGoods> selectByExample(StoreGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    StoreGoods selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") StoreGoods record, @Param("example") StoreGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") StoreGoods record, @Param("example") StoreGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByExample(@Param("record") StoreGoods record, @Param("example") StoreGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByPrimaryKeySelective(StoreGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(StoreGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    int updateByPrimaryKey(StoreGoods record);
}