package com.pdd.userMgr.service.po;

import java.util.Date;

public class StoreUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.depth
     *
     * @mbggenerated
     */
    private String depth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.invitation
     *
     * @mbggenerated
     */
    private String invitation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.generated
     *
     * @mbggenerated
     */
    private String generated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.txpath
     *
     * @mbggenerated
     */
    private String txpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.salt
     *
     * @mbggenerated
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.shop_id
     *
     * @mbggenerated
     */
    private String shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.id
     *
     * @return the value of store_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.id
     *
     * @param id the value for store_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.username
     *
     * @return the value of store_user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.username
     *
     * @param username the value for store_user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.mobile
     *
     * @return the value of store_user.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.mobile
     *
     * @param mobile the value for store_user.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.password
     *
     * @return the value of store_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.password
     *
     * @param password the value for store_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.depth
     *
     * @return the value of store_user.depth
     *
     * @mbggenerated
     */
    public String getDepth() {
        return depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.depth
     *
     * @param depth the value for store_user.depth
     *
     * @mbggenerated
     */
    public void setDepth(String depth) {
        this.depth = depth == null ? null : depth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.path
     *
     * @return the value of store_user.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.path
     *
     * @param path the value for store_user.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.invitation
     *
     * @return the value of store_user.invitation
     *
     * @mbggenerated
     */
    public String getInvitation() {
        return invitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.invitation
     *
     * @param invitation the value for store_user.invitation
     *
     * @mbggenerated
     */
    public void setInvitation(String invitation) {
        this.invitation = invitation == null ? null : invitation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.generated
     *
     * @return the value of store_user.generated
     *
     * @mbggenerated
     */
    public String getGenerated() {
        return generated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.generated
     *
     * @param generated the value for store_user.generated
     *
     * @mbggenerated
     */
    public void setGenerated(String generated) {
        this.generated = generated == null ? null : generated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.txpath
     *
     * @return the value of store_user.txpath
     *
     * @mbggenerated
     */
    public String getTxpath() {
        return txpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.txpath
     *
     * @param txpath the value for store_user.txpath
     *
     * @mbggenerated
     */
    public void setTxpath(String txpath) {
        this.txpath = txpath == null ? null : txpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.update_date
     *
     * @return the value of store_user.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.update_date
     *
     * @param updateDate the value for store_user.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.type
     *
     * @return the value of store_user.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.type
     *
     * @param type the value for store_user.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.salt
     *
     * @return the value of store_user.salt
     *
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.salt
     *
     * @param salt the value for store_user.salt
     *
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.shop_id
     *
     * @return the value of store_user.shop_id
     *
     * @mbggenerated
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.shop_id
     *
     * @param shopId the value for store_user.shop_id
     *
     * @mbggenerated
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.create_time
     *
     * @return the value of store_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.create_time
     *
     * @param createTime the value for store_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}