package com.pdd.userMgr.service.po;

import java.util.Date;

public class StoreShop {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_shop.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_shop.shop_name
     *
     * @mbggenerated
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_shop.generated
     *
     * @mbggenerated
     */
    private String generated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_shop.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_shop.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_shop.identity_card
     *
     * @mbggenerated
     */
    private String identityCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_shop.Status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_shop.Phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_shop.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_shop.id
     *
     * @return the value of store_shop.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_shop.id
     *
     * @param id the value for store_shop.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_shop.shop_name
     *
     * @return the value of store_shop.shop_name
     *
     * @mbggenerated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_shop.shop_name
     *
     * @param shopName the value for store_shop.shop_name
     *
     * @mbggenerated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_shop.generated
     *
     * @return the value of store_shop.generated
     *
     * @mbggenerated
     */
    public String getGenerated() {
        return generated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_shop.generated
     *
     * @param generated the value for store_shop.generated
     *
     * @mbggenerated
     */
    public void setGenerated(String generated) {
        this.generated = generated == null ? null : generated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_shop.create_date
     *
     * @return the value of store_shop.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_shop.create_date
     *
     * @param createDate the value for store_shop.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_shop.password
     *
     * @return the value of store_shop.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_shop.password
     *
     * @param password the value for store_shop.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_shop.identity_card
     *
     * @return the value of store_shop.identity_card
     *
     * @mbggenerated
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_shop.identity_card
     *
     * @param identityCard the value for store_shop.identity_card
     *
     * @mbggenerated
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard == null ? null : identityCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_shop.Status
     *
     * @return the value of store_shop.Status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_shop.Status
     *
     * @param status the value for store_shop.Status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_shop.Phone_number
     *
     * @return the value of store_shop.Phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_shop.Phone_number
     *
     * @param phoneNumber the value for store_shop.Phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_shop.level
     *
     * @return the value of store_shop.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_shop.level
     *
     * @param level the value for store_shop.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}