package com.pdd.userMgr.service.po;

import java.math.BigDecimal;

public class StoreUserRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user_record.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user_record.consume
     *
     * @mbggenerated
     */
    private BigDecimal consume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user_record.credits
     *
     * @mbggenerated
     */
    private BigDecimal credits;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user_record.id
     *
     * @return the value of store_user_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user_record.id
     *
     * @param id the value for store_user_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user_record.user_id
     *
     * @return the value of store_user_record.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user_record.user_id
     *
     * @param userId the value for store_user_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user_record.consume
     *
     * @return the value of store_user_record.consume
     *
     * @mbggenerated
     */
    public BigDecimal getConsume() {
        return consume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user_record.consume
     *
     * @param consume the value for store_user_record.consume
     *
     * @mbggenerated
     */
    public void setConsume(BigDecimal consume) {
        this.consume = consume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user_record.credits
     *
     * @return the value of store_user_record.credits
     *
     * @mbggenerated
     */
    public BigDecimal getCredits() {
        return credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user_record.credits
     *
     * @param credits the value for store_user_record.credits
     *
     * @mbggenerated
     */
    public void setCredits(BigDecimal credits) {
        this.credits = credits;
    }
}