package com.pdd.userMgr.service.po;

import java.util.Date;

public class StoreUserAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user_address.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user_address.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user_address.the_consignee
     *
     * @mbggenerated
     */
    private String theConsignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user_address.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user_address.area_id
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user_address.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user_address.is_choice
     *
     * @mbggenerated
     */
    private Byte isChoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user_address.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user_address.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user_address.id
     *
     * @return the value of store_user_address.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user_address.id
     *
     * @param id the value for store_user_address.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user_address.user_id
     *
     * @return the value of store_user_address.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user_address.user_id
     *
     * @param userId the value for store_user_address.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user_address.the_consignee
     *
     * @return the value of store_user_address.the_consignee
     *
     * @mbggenerated
     */
    public String getTheConsignee() {
        return theConsignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user_address.the_consignee
     *
     * @param theConsignee the value for store_user_address.the_consignee
     *
     * @mbggenerated
     */
    public void setTheConsignee(String theConsignee) {
        this.theConsignee = theConsignee == null ? null : theConsignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user_address.phone
     *
     * @return the value of store_user_address.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user_address.phone
     *
     * @param phone the value for store_user_address.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user_address.area_id
     *
     * @return the value of store_user_address.area_id
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user_address.area_id
     *
     * @param areaId the value for store_user_address.area_id
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user_address.address
     *
     * @return the value of store_user_address.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user_address.address
     *
     * @param address the value for store_user_address.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user_address.is_choice
     *
     * @return the value of store_user_address.is_choice
     *
     * @mbggenerated
     */
    public Byte getIsChoice() {
        return isChoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user_address.is_choice
     *
     * @param isChoice the value for store_user_address.is_choice
     *
     * @mbggenerated
     */
    public void setIsChoice(Byte isChoice) {
        this.isChoice = isChoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user_address.create_date
     *
     * @return the value of store_user_address.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user_address.create_date
     *
     * @param createDate the value for store_user_address.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user_address.update_date
     *
     * @return the value of store_user_address.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user_address.update_date
     *
     * @param updateDate the value for store_user_address.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}