package com.pdd.shopMgr.service.po;

import java.util.Date;

public class StoreArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_area.id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_area.name
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_area.short_name
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_area.type
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_area.sort
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private Long sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_area.description
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_area.parent_id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_area.create_date
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_area.id
     *
     * @return the value of store_area.id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_area.id
     *
     * @param id the value for store_area.id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_area.name
     *
     * @return the value of store_area.name
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_area.name
     *
     * @param name the value for store_area.name
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_area.short_name
     *
     * @return the value of store_area.short_name
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_area.short_name
     *
     * @param shortName the value for store_area.short_name
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_area.type
     *
     * @return the value of store_area.type
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_area.type
     *
     * @param type the value for store_area.type
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_area.sort
     *
     * @return the value of store_area.sort
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_area.sort
     *
     * @param sort the value for store_area.sort
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_area.description
     *
     * @return the value of store_area.description
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_area.description
     *
     * @param description the value for store_area.description
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_area.parent_id
     *
     * @return the value of store_area.parent_id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_area.parent_id
     *
     * @param parentId the value for store_area.parent_id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_area.create_date
     *
     * @return the value of store_area.create_date
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_area.create_date
     *
     * @param createDate the value for store_area.create_date
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}