package com.pdd.shopMgr.service.po;

import java.util.Date;

public class StoreDict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_dict.id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_dict.label
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_dict.value
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_dict.type
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_dict.description
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_dict.parent_id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_dict.create_date
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_dict.sort
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private Long sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_dict.id
     *
     * @return the value of store_dict.id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_dict.id
     *
     * @param id the value for store_dict.id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_dict.label
     *
     * @return the value of store_dict.label
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_dict.label
     *
     * @param label the value for store_dict.label
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_dict.value
     *
     * @return the value of store_dict.value
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_dict.value
     *
     * @param value the value for store_dict.value
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_dict.type
     *
     * @return the value of store_dict.type
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_dict.type
     *
     * @param type the value for store_dict.type
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_dict.description
     *
     * @return the value of store_dict.description
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_dict.description
     *
     * @param description the value for store_dict.description
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_dict.parent_id
     *
     * @return the value of store_dict.parent_id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_dict.parent_id
     *
     * @param parentId the value for store_dict.parent_id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_dict.create_date
     *
     * @return the value of store_dict.create_date
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_dict.create_date
     *
     * @param createDate the value for store_dict.create_date
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_dict.sort
     *
     * @return the value of store_dict.sort
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_dict.sort
     *
     * @param sort the value for store_dict.sort
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }
}