package com.pdd.shopMgr.service.po;

import java.math.BigDecimal;

public class StoreShopGoodsRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_shop_goods_relation.id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_shop_goods_relation.shop_id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private String shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_shop_goods_relation.good_id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private String goodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_shop_goods_relation.is_enable
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private Byte isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_shop_goods_relation.price
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_shop_goods_relation.id
     *
     * @return the value of store_shop_goods_relation.id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_shop_goods_relation.id
     *
     * @param id the value for store_shop_goods_relation.id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_shop_goods_relation.shop_id
     *
     * @return the value of store_shop_goods_relation.shop_id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_shop_goods_relation.shop_id
     *
     * @param shopId the value for store_shop_goods_relation.shop_id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_shop_goods_relation.good_id
     *
     * @return the value of store_shop_goods_relation.good_id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public String getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_shop_goods_relation.good_id
     *
     * @param goodId the value for store_shop_goods_relation.good_id
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setGoodId(String goodId) {
        this.goodId = goodId == null ? null : goodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_shop_goods_relation.is_enable
     *
     * @return the value of store_shop_goods_relation.is_enable
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public Byte getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_shop_goods_relation.is_enable
     *
     * @param isEnable the value for store_shop_goods_relation.is_enable
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setIsEnable(Byte isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_shop_goods_relation.price
     *
     * @return the value of store_shop_goods_relation.price
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_shop_goods_relation.price
     *
     * @param price the value for store_shop_goods_relation.price
     *
     * @mbggenerated Mon Mar 26 13:00:16 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}